provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  billing:
    lang: golang-middleware
    handler: ./billing
    image: wilsonianbcoil/system-billing
    build_args:
      GO111MODULE: on
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - billing_config.yml
    environment:
      balances_key_prefix: "balances"
      prometheus_host: prometheus.openfaas
      prometheus_port: 9090
      redis_uri: "redis.openfaas:6379"
      write_debug: true
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m
  receipt-verifier:
    lang: node12
    handler: ./receipt-verifier
    image: wilsonianbcoil/receipt-verifier-fn
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - receipt_verifier_config.yml
    environment:
      balances_key_prefix: "balances"
      receipt_verifier_uri: "http://receipt-verifier.openfaas:3000"
      redis_uri: "redis.openfaas:6379"
      write_debug: true
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m
  revshare:
    lang: golang-middleware
    handler: ./revshare
    image: wilsonianbcoil/system-revshare
    build_args:
      GO111MODULE: on
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - revshare_config.yml
    environment:
      basic_auth: true
      gateway_url: "http://gateway.openfaas:8080/"
      secret_mount_path: /var/openfaas/secrets
      write_debug: true
    secrets:
      - basic-auth-user
      - basic-auth-password
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m
