provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  billing:
    lang: go
    handler: ./billing
    image: wilsonianbcoil/system-billing
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - billing_config.yml
    environment:
      balances_url: "http://receipt-verifier.openfaas:3000"
      prometheus_host: prometheus.openfaas
      prometheus_port: 9090
      write_debug: true
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m
