provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  billing:
    lang: go
    handler: ./billing
    image: wilsonianbcoil/system-billing
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - billing_config.yml
    environment:
      balances_url: "http://receipt-verifier.openfaas:3000"
      prometheus_host: prometheus.openfaas
      prometheus_port: 9090
      write_debug: true
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m
  revshare:
    lang: go
    handler: ./revshare
    image: wilsonianbcoil/system-revshare
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - revshare_config.yml
    environment:
      basic_auth: true
      gateway_url: "http://gateway.openfaas:8080/"
      secret_mount_path: /var/openfaas/secrets
      write_debug: true
    secrets:
      - basic-auth-user
      - basic-auth-password
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m
