provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  billing:
    lang: golang-middleware
    handler: ./billing
    image: ghcr.io/${REPO:-codius}/ofc-billing:${TAG:-dev}
    build_args:
      GO111MODULE: on
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      cost_per_unit_invocations: ${cost_per_unit_invocations:-10}
      unit_invocations: ${unit_invocations:-1000}
      bonus_invocations: ${bonus_invocations:-50}
      balances_key_prefix: "balances"
      prometheus_host: prometheus.openfaas
      prometheus_port: 9090
      redis_uri: "redis.openfaas:6379"
      write_debug: true
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m
  receipt-verifier:
    lang: node12
    handler: ./receipt-verifier
    image: ghcr.io/${REPO:-codius}/ofc-receipt-verifier:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      balances_key_prefix: "balances"
      payment_pointer: ${payment_pointer:-https://wallet/account}
      receipt_verifier_uri: "http://receipt-verifier.openfaas:3000"
      redis_uri: "redis.openfaas:6379"
      write_debug: true
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m
  revshare:
    lang: golang-middleware
    handler: ./revshare
    image: ghcr.io/${REPO:-codius}/ofc-revshare:${TAG:-dev}
    build_args:
      GO111MODULE: on
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      basic_auth: true
      gateway_url: "http://gateway.openfaas:8080/"
      payment_pointer: ${payment_pointer:-https://wallet/account}
      secret_mount_path: /var/openfaas/secrets
      write_debug: true
    secrets:
      - basic-auth-user
      - basic-auth-password
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m
