apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-verifier
spec:
  template:
    spec:
      containers:
      - name: receipt-verifier
        env:
        - name: REDIS_URI
          value: redis://redis.openfaas:6379/
        - name: SPSP_ENDPOINTS_URL
          value: http://gateway.openfaas:8080/function/revshare
