apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-auth
spec:
  template:
    spec:
      containers:
      - name: edge-auth
        image: ghcr.io/codius/ofc-edge-auth:latest
        imagePullPolicy: Always
