namespace: openfaas

bases:
- github.com/wilsonianb/openfaas-cloud/yaml/core

patchesStrategicMerge:
- edge_auth_image_patch.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: edge-auth
  path: edge_auth_patch.yaml
