apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-auth
spec:
  template:
    spec:
      containers:
      - name: edge-auth
        image: wilsonianbcoil/edge-auth
        imagePullPolicy: Always
