varReference:
- path: spec/tls/secretName
  kind: Ingress
- path: spec/runtimeClassName
  kind: Profile
- path: data/github_app_url
  kind: ConfigMap
- path: data/payment_pointer
  kind: ConfigMap
- path: data/receipts_url
  kind: ConfigMap
