bases:
- ../remote

resources:
- gateway-function-ingress.yaml
- profile.yaml
- wm-ingress.yaml
- workload-net-policy.yaml

configMapGenerator:
- name: system-dashboard
  namespace: openfaas-fn
  literals:
  - github_app_url=$(GithubAppUrl)
  - payment_pointer=$pay.$(RootDomain)
  - receipts_url=https://pay.$(RootDomain)/receipts
  files:
  - pub-cert.pem

generatorOptions:
  disableNameSuffixHash: true

configurations:
- kustomizeconfig.yaml
